export const Userdata = [
    {
      name: 'Jan',
      "Active System": 4000,
      "Patch Installation": 2400,
      amt: 2400,
    },
    {
      name: 'Feb',
      "Active System": 3000,
      "Patch Installation": 1398,
      amt: 2210,
    },
    {
      name: 'Mar',
      "Active System": 2000,
      "Patch Installation": 5800,
      amt: 2290,
    },
    {
      name: 'Apr',
      "Active System": 2780,
      "Patch Installation": 3908,
      amt: 2000,
    },
    {
      name: 'May',
      "Active System": 1890,
      "Patch Installation": 4800,
      amt: 2181,
    },
    {
      name: 'June',
      "Active System": 2390,
      "Patch Installation": 3800,
      amt: 2500,
    },
    {
      name: 'July',
      "Active System": 3490,
      "Patch Installation": 4300,
      amt: 2100,
    },
    {
        name: 'August',
        "Active System": 2490,
        "Patch Installation": 5600,
        amt: 2100,
      },
      {
        name: 'Sepember',
        "Active System": 1890,
        "Patch Installation": 4500,
        amt: 2100,
      },
      {
        name: 'October',
        "Active System": 3789,
        "Patch Installation": 1200,
        amt: 2100,
      },
      {
        name: 'November',
        "Active System": 2110,
        "Patch Installation": 3900,
        amt: 2100,
      },   
      {
        name: 'December',
        "Active System": 2022,
        "Patch Installation": 5100,
        amt: 2100,
      },  
  ];

export const userRows = [
    { id: 1,
      username: 'Test User', 
      email: 'testuser@example.com', 
      status: "active",
      jobRoll: 'Admin Test',
      StartDate: '01 Jan 2022',
     },
     { id: 2,
        username: 'Test User', 
        email: 'testuser@example.com', 
        status: "active",
        jobRoll: 'Admin Test',
        StartDate: '01 Jan 2022',
       },
       { id: 3,
        username: 'Test User', 
        email: 'testuser@example.com', 
        status: "active",
        jobRoll: 'Admin Test',
        StartDate: '01 Jan 2022',
       },
       { id: 4,
        username: 'Test User', 
        email: 'testuser@example.com', 
        status: "active",
        jobRoll: 'Admin Test',
        StartDate: '01 Jan 2022',
       },
       { id: 5,
        username: 'Test User', 
        email: 'testuser@example.com', 
        status: "active",
        jobRoll: 'Admin Test',
        StartDate: '01 Jan 2022',
       },
       { id: 6,
        username: 'Test User', 
        email: 'testuser@example.com', 
        status: "active",
        jobRoll: 'Admin Test',
        StartDate: '01 Jan 2022',
       },
       { id: 7,
        username: 'Test User', 
        email: 'testuser@example.com', 
        status: "active",
        jobRoll: 'Admin Test',
        StartDate: '01 Jan 2022',
       },
       { id: 8,
        username: 'Test User', 
        email: 'testuser@example.com', 
        status: "active",
        jobRoll: 'Admin Test',
        StartDate: '01 Jan 2022',
       },
       { id: 9,
        username: 'Test User', 
        email: 'testuser@example.com', 
        status: "active",
        jobRoll: 'Admin Test',
        StartDate: '01 Jan 2022',
       },
       { id: 10,
        username: 'Test User', 
        email: 'testuser@example.com', 
        status: "active",
        jobRoll: 'Admin Test',
        StartDate: '01 Jan 2022',
       },
        ];

        export const deviceRows = [
          { id: 1,
            devicename: 'Test User', 
            os: 'testuser@example.com', 
            osversion: "active",
            patchDate: '01 Jan 2022',
            userId: '1'
           },
           { id: 2,
            devicename: 'Test User', 
            os: 'testuser@example.com', 
            osversion: "active",
            patchDate: '01 Jan 2022',
            userId: '1'
           },
           { id: 3,
            devicename: 'Test User', 
            os: 'testuser@example.com', 
            osversion: "active",
            patchDate: '01 Jan 2022',
            userId: '1'
           },
           { id: 4,
            devicename: 'Test User', 
            os: 'testuser@example.com', 
            osversion: "active",
            patchDate: '01 Jan 2022',
            userId: '1'
           },
           { id: 5,
            devicename: 'Test User', 
            os: 'testuser@example.com', 
            osversion: "active",
            patchDate: '01 Jan 2022',
            userId: '1'
           },
           { id: 6,
            devicename: 'Test User', 
            os: 'testuser@example.com', 
            osversion: "active",
            patchDate: '01 Jan 2022',
            userId: '1'
           },
           { id: 7,
            devicename: 'Test User', 
            os: 'testuser@example.com', 
            osversion: "active",
            patchDate: '01 Jan 2022',
            userId: '1'
           },
           { id: 8,
            devicename: 'Test User', 
            os: 'testuser@example.com', 
            osversion: "active",
            patchDate: '01 Jan 2022',
            userId: '1'
           },
           { id: 9,
            devicename: 'Test User', 
            os: 'testuser@example.com', 
            osversion: "active",
            patchDate: '01 Jan 2022',
            userId: '1'
           },
           { id: 10,
            devicename: 'Test User', 
            os: 'testuser@example.com', 
            osversion: "active",
            patchDate: '01 Jan 2022',
            userId: '1'
           }
              ];  